services:
  orchestrator-agent:
    build: agents/orchestrator_agent
    ports:
      - "8001:8000"
    environment:
      - DATA_INGESTOR_URL=http://data-ingestor-agent:8000
      - SUMMARIZATION_URL=http://summarization-agent:8000
      - SENTIMENT_URL=http://sentiment-agent:8000
      - SEMANTIC_SEARCH_URL=http://semantic-search-agent:8000
      - QA_URL=http://qa-agent:8000
      - ANALYTICS_URL=http://analytics-agent:8000
    depends_on:
      - data-ingestor-agent
      - summarization-agent
      - sentiment-agent
      - semantic-search-agent
      - qa-agent
      - analytics-agent

  data-ingestor-agent:
    build:                                                                                                                                              
       context: ./agents/data_ingestor_agent                                                                                                             
       dockerfile: Dockerfile                                                                                                                            
    ports:                                                                                                                                              
       - "8010:8000"                                                                                                                                     
    environment:                                                                                                                                        
       - KAFKA_BROKERS=kafka:9092                                                                                                                        
       - SEC_API_KEY=${SEC_API_KEY}                                                                                                                      
       - PROMETHEUS_MULTIPROC_DIR=/app/metrics                                                                                                           
    healthcheck:                                                                                                                                        
       test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]                                                                             
       interval: 30s                                                                                                                                     
       timeout: 10s                                                                                                                                      
       retries: 3                                                                                                                                        
       start_period: 30s                                                                                                                                 
    volumes:                                                                                                                                            
       - ./metrics:/app/metrics                                                                                                                          
    depends_on:                                                                                                                                         
       kafka:                                                                                                                                            
         condition: service_healthy
  kafka:                                                                                                                                                
     image: confluentinc/cp-kafka:7.4.0                                                                                                                  
     healthcheck:                                                                                                                                        
       test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]                                                                
       interval: 10s                                                                                                                                     
       timeout: 5s                                                                                                                                       
       retries: 5                                                                                                                                        
     environment:                                                                                                                                        
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1                                                                                                         
       KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0                                                                                                         
     ports:                                                                                                                                              
       - "9092:9092"    

  semantic-search-agent:
    build: agents/semantic_search_agent
    ports:
      - "8020:8000"

  sentiment-agent:
    build: agents/sentiment_agent
    ports:
      - "8030:8000"

  summarization-agent:
    build: agents/summarization_agent
    ports:
      - "8040:8000"

  qa-agent:
    build: agents/qa_agent
    ports:
      - "8050:8000"

  analytics-agent:
    build: agents/analytics_agent
    ports:
      - "8060:8000"